<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ahatornn.TestGenerator" Version="1.1.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Moq" Version="4.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BillSale.DAL.Context\BillSale.DAL.Context.csproj" />
    <ProjectReference Include="..\BillSale.DAL.Contracts\BillSale.DAL.Contracts.csproj" />
  </ItemGroup>

</Project>
